### ISSUE TITLE
Do not force link openssl

### ISSUE THREAD

**Issue by timurvafin** [fs/osx-bootstrap#112]
Looks like we can't link openssl anymore and this is prohibited[1] and we need to find better way[2].

1: https://github.com/Homebrew/brew/issues/891
2: https://github.com/eventmachine/eventmachine/issues/661

**Comment by vladimirbazhanov** [comment]
Can you pls describe (or put some link) why we need to compile Ruby with openssl from brew? May be today this is not actual and we can use openssl from OS?
