### ISSUE TITLE
Pgcli

### ISSUE THREAD

**Issue by IlkhamGaysin** [fs/osx-bootstrap#90]
How about adding the command line interface for Postgres:
http://pgcli.com/

**Comment by IlkhamGaysin** [comment]
@timurvafin Please take it look!

**Comment by timurvafin** [comment]
@IlkhamGaysin looks awesome, but I'm not sure we need to require this dependency to be installed for all macs. 

You can add commented line to https://github.com/fs/dotfiles/blob/master/brew/Brewfile.symlink.example to let other develops know about it and share that it on Demo day!
